[package]
name = "otto"
version = "0.1.0"
authors = ["Rollie Ma <rollie@rollie.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
clap = "3.0.0-beta.2"
crossbeam-channel = "0.5.0"
ctrlc = "3.1.7"
job_scheduler = "1.2.1"
log = "0.4.11"
reqwest = { version = "0.11.0", features = ["blocking"] }
serde = "1.0.118"
serde_derive = "1.0.118"
simple_logger = "1.11.0"
slack-hook = "0.8.0"
toml = "0.5.8"
